---
title: "population_wrangle"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(acs)
acs_key <- "3f58748f63ce427e4133d32fd5b094e102b4ec31"
big_geo <- geo.make(state = 36, county = c("Albany", "Allegany", "Broome",
                                           "Cattaraugus", "Cayuga",
                                           "Chautauqua", "Chemung", "Chenango",
                                           "Clinton", "Columbia", "Cortland",
                                           "Delaware", "Dutchess", "Erie",
                                           "Essex", "Franklin", "Fulton",
                                           "Genesee", "Greene", "Hamilton",
                                           "Herkimer", "Jefferson", "Lewis",
                                           "Livingston", "Madison", "Monroe",
                                           "Montgomery", "Nassau", "Niagara",
                                           "Oneida", "Onondaga", "Ontario",
                                           "Orange", "Orleans", "Oswego",
                                           "Otsego", "Putnam", "Rensselaer",
                                           "Rockland", "St. Lawrence", "Saratoga",
                                           "Schenectady", "Schoharie", "Schuyler",
                                           "Seneca", "Steuben", "Suffolk",
                                           "Sullivan", "Tioga", "Tompkins",
                                           "Ulster", "Warren", "Washington",
                                           "Wayne", "Westchester", "Wyoming",
                                           "Yates"))
```

```{r}
bigPop_2015 <- acs.fetch(geo = big_geo, endyear = 2015, table.number ="B01003", key = acs_key)
bigPop_2014 <- acs.fetch(geo = big_geo, endyear = 2014, table.number ="B01003", key = acs_key)
bigPop_2013 <- acs.fetch(geo = big_geo, endyear = 2013, table.number ="B01003", key = acs_key)
bigPop_2012 <- acs.fetch(geo = big_geo, endyear = 2012, table.number ="B01003", key = acs_key)
bigPop_2011 <- acs.fetch(geo = big_geo, endyear = 2011, table.number ="B01003", key = acs_key)
bigPop_2010 <- acs.fetch(geo = big_geo, endyear = 2010, table.number ="B01003", key = acs_key)
bigPop_2009 <- acs.fetch(geo = big_geo, endyear = 2009, table.number ="B01003", key = acs_key)


bigIncome_2015 <- acs.fetch(geo = big_geo, endyear = 2015, table.number =  "B19013", key = acs_key)
bigIncome_2014 <- acs.fetch(geo = big_geo, endyear = 2014, table.number =  "B19013", key = acs_key)
bigIncome_2013 <- acs.fetch(geo = big_geo, endyear = 2013, table.number =  "B19013", key = acs_key)
bigIncome_2012 <- acs.fetch(geo = big_geo, endyear = 2012, table.number =  "B19013", key = acs_key)
bigIncome_2011 <- acs.fetch(geo = big_geo, endyear = 2011, table.number =  "B19013", key = acs_key)
bigIncome_2010 <- acs.fetch(geo = big_geo, endyear = 2010, table.number =  "B19013", key = acs_key)
bigIncome_2009 <- acs.fetch(geo = big_geo, endyear = 2009, table.number =  "B19013", key = acs_key)
```

```{r}
library(dplyr)

pop_2015 <- as.data.frame(bigPop_2015@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county, B01003_001) %>% 
  rename("population_2015" = B01003_001) 

pop_2014 <- as.data.frame(bigPop_2014@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county, B01003_001) %>% 
  rename("population_2014" = B01003_001) 

pop_2013 <- as.data.frame(bigPop_2013@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county, B01003_001) %>% 
  rename("population_2013" = B01003_001) 

pop_2012 <- as.data.frame(bigPop_2012@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county, B01003_001) %>% 
  rename("population_2012" = B01003_001) 

pop_2011 <- as.data.frame(bigPop_2011@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county, B01003_001) %>% 
  rename("population_2011" = B01003_001) 

pop_2010 <- as.data.frame(bigPop_2010@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county, B01003_001) %>% 
  rename("population_2010" = B01003_001) 

pop_2009 <- as.data.frame(bigPop_2009@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county, B01003_001) %>% 
  rename("population_2009" = B01003_001) 

income_2015 <- as.data.frame(bigIncome_2015@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county,B19013_001) %>% 
  rename("income_2015" = B19013_001)

income_2014 <- as.data.frame(bigIncome_2014@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county,B19013_001) %>% 
  rename("income_2014" = B19013_001)

income_2013 <- as.data.frame(bigIncome_2013@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county,B19013_001) %>% 
  rename("income_2013" = B19013_001)

income_2012 <- as.data.frame(bigIncome_2012@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county,B19013_001) %>% 
  rename("income_2012" = B19013_001)

income_2011 <- as.data.frame(bigIncome_2011@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county,B19013_001) %>% 
  rename("income_2011" = B19013_001)

income_2010 <- as.data.frame(bigIncome_2010@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county,B19013_001) %>% 
  rename("income_2010" = B19013_001)

income_2009 <- as.data.frame(bigIncome_2009@estimate) %>% 
  mutate(county_full = rownames(.),
         county = str_replace(county_full,"(.+) County.*","\\1")) %>% 
  select(county,B19013_001) %>% 
  rename("income_2009" = B19013_001)
```


```{r}
acs_pop <- pop_2015 %>%
  inner_join(pop_2014, by = "county") %>%
  inner_join(pop_2013, by = "county") %>%
  inner_join(pop_2012, by = "county") %>%
  inner_join(pop_2011, by = "county") %>%
  inner_join(pop_2010, by = "county") %>%
  inner_join(pop_2009, by = "county") %>% 
  gather("year", "population", 2:8) %>%
  mutate(year = gsub("population_", "", year)) %>%
  mutate(year = as.numeric(year))

acs_income <- income_2015 %>%
  inner_join(income_2014, by = "county") %>%
  inner_join(income_2013, by = "county") %>%
  inner_join(income_2012, by = "county") %>%
  inner_join(income_2011, by = "county") %>%
  inner_join(income_2010, by = "county") %>%
  inner_join(income_2009, by = "county") %>%
  gather("year", "income", 2:8) %>%
  mutate(year = gsub("income_", "", year)) %>%
  mutate(year = as.numeric(year))

acs <- acs_pop %>%
  inner_join(acs_income, by = c("county", "year"))

names(acs)[1] <- "County"
```

```{r}
save(acs, file="acs.Rda")
```
