---
title: "New York Real Estate Trends"
author: ''
date: ''
output:
  html_document:
    fig_height: 3
    fig_width: 5
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)# Load additional packages here 
library(RMySQL)
library(ggmap)
library(tidyverse)
library(lubridate)
library(leaflet)
# Some customization.  You can alter or delete as desired (if you know what you are doing).
trellis.par.set(theme=theme.mosaic()) # change default color scheme for lattice
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

```{r, include = FALSE}
load("nyhousing_transactions.Rda")
```

```{r, include = FALSE}
transactions_2017 <- transactions %>%
  filter(year == 2017) %>%
  select(County, Town, SalePrice, Long, Lat, SaleDate, address_full)
```

```{r}
pal <- colorNumeric(
  palette = "YlOrRd",
  domain = log(transactions_2017$SalePrice)
)
```

```{r}
m <- transactions_2017 %>%
  select(SalePrice, Long, Lat) %>%
  leaflet() %>%
  addTiles() %>%  
  addCircles(lng = ~Long, lat = ~Lat, radius = 10,
                   color = ~pal(log(SalePrice)), opacity = 5) #%>%
  #addMiniMap()
  #addLegend("bottomright", pal = pal, values = ~log(SalePrice),
            #title = "Log(Sale Price)", opacity = 1)
m
```


``{r}
map <- get_map(location = 'Albany, NY', maptype = "roadmap")
ggmap(map) + 
  geom_point(aes(x = lon, y = lat, col = log(SalePrice)),
             data = albany_2017, size = 1, alpha = .2, position = "jitter") +
  scale_color_gradient(low = "Blue", high = "Red")
  
```

