---
title: "Reading and Saving SQL Data"
author: "Robbie Zielinski"
date: "4/24/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RMySQL)
library(tidyverse)
library(lubridate)
```

```{r, include = FALSE}
db <- dbConnect(MySQL(), user = 'stat231', password = 'stat231project', dbname = "nyhousing", host = '148.85.253.214')
transactions <- tbl(db, "transactions2")
```

```{r, include = FALSE}
transactions <- collect(transactions)
transactions <- transactions %>%
mutate(SaleDate = mdy(SaleDate),
month = as.numeric(month),
day = as.numeric(day),
year = as.numeric(year),
SalePrice = as.numeric(SalePrice),
Long = lon,
Lat = lat) %>%
filter(Lat > 40 & Lat < 46) %>%
filter(Long > -80 & Long < -70)
```

```{r}
counties <- c("Albany", "Allegany", "Broome", "Cattaraugus", "Cayuga",
"Chautauqua", "Chemung", "Chenango", "Clinton", "Columbia",
"Cortland", "Delaware", "Dutchess", "Erie", "Essex", "Franklin",
"Fulton", "Genesee", "Greene", "Hamilton", "Herkimer", "Jefferson",
"Lewis", "Livingston", "Madison", "Monroe", "Montgomery",
"Nassau", "Niagara", "Oneida", "Onondaga", "Ontario", "Orange",
"Orleans", "Oswego", "Otsego", "Putnam", "Rensselaer", "Rockland",
"St. Lawrence", "Saratoga", "Schenectady", "Schoharie",
"Schuyler", "Seneca", "Steuben", "Suffolk", "Sullivan",
"Tioga", "Tompkins", "Ulster", "Warren", "Washington", "Wayne",
"Westchester", "Wyoming", "Yates")

long_min <- c(-74.3, -78.3, -76.2, -79.1, -76.8, -79.8, -77.0, -75.9, -74.0, -74.0,
-76.3, -75.5, -74.0, -79.2, -74.4, -74.8, -74.8, -78.5, -74.6, -74.9,
-75.3, -76.5, -75.9, -78.1, -76.0, -78.0, -74.8, -73.8, -79.1, -75.9,
-76.5, -77.7, -74.8, -78.5, -76.7, -75.5, -74.0, -73.8, -74.3, -75.9,
-74.2, -74.4, -74.8, -77.1, -77.0, -77.8, -73.5, -75.2, -76.6, -76.7,
-74.8, -74.3, -73.7, -77.4, -74.0, -78.5, -77.4)

long_max <- c(-73.6, -77.7, -75.3, -78.3, -76.2, -79.0, -76.5, -75.3, -73.3, -73.3,
-75.8, -74.4, -73.4, -78.4, -73.3, -73.9, -74.1, -77.9, -73.7, -74.0,
-74.6, -75.4, -75.1, -77.4, -75.2, -77.3, -74.0, -73.4, -78.4, -75.0,
-75.8, -76.9, -73.9, -77.9, -75.7, -74.6, -73.5, -73.2, -73.9, -74.5,
-73.5, -73.8, -74.1, -76.6, -76.6, -76.9, -71.8, -74.3, -76.0, -76.2,
-73.9, -73.4, -73.2, -76.7, -73.4, -77.9, -76.9)

lat_min <- c(42.4, 42.0, 42.0, 42.0, 42.6, 42.0, 42.0, 42.2, 44.4, 41.9, 42.4, 41.8,
41.4, 42.4, 43.7, 44.0, 42.9, 42.8, 42.0, 43.2, 42.8, 43.6, 43.4, 42.4,
42.7, 42.9, 42.7, 40.5, 43.0, 42.8, 42.7, 42.5, 41.1, 43.1, 43.1, 42.3,
41.3, 42.4, 40.9, 44.0, 42.7, 42.7, 42.3, 42.2, 42.5, 42.0, 40.6, 41.4,
42.0, 42.2, 41.5, 43.2, 42.9, 43.0, 40.8, 42.5, 42.4)

lat_max <- c(42.9, 42.6, 42.5, 42.6, 43.5, 42.6, 42.3, 42.8, 45.0, 42.5, 42.8, 42.6,
42.1, 43.1, 44.6, 45.0, 43.3, 43.2, 42.5, 44.2, 44.1, 44.4, 44.3, 43.0,
43.2, 43.4, 43.1, 41.0, 43.4, 43.6, 43.3, 43.0, 41.7, 43.4, 43.7, 42.9,
41.6, 43.0, 41.4, 45.1, 43.4, 43.0, 42.9, 42.6, 43.1, 42.6, 41.3, 42.0,
42.5, 42.7, 42.2, 43.8, 43.8, 43.4, 41.4, 42.9, 42.8)

counties_lat_lon <- data.frame(counties, long_min, long_max, lat_min, lat_max)
```

```{r}
transactions <- transactions %>%
left_join(counties_lat_lon, by = c("County" = "counties"))

transactions <- transactions %>%
mutate(Long = ifelse((Long > long_min & Long < long_max & Lat > lat_min & Lat < lat_max), Long, NA),
Lat = ifelse((Long > long_min & Long < long_max & Lat > lat_min & Lat < lat_max), Lat, NA))


transactions <- transactions %>%
select(County, Town, Address, ZipCode, SalePrice, SaleDate, SellerName, BuyerName,
id, address_full, Long, Lat, month, day, year)
```

```{r}
save(transactions, file="nyhousing_transactions.Rda")
```
